### PR TITLE
bugfix: Remove forced default width, forced full-width

### PR DESCRIPTION
**Pull request by jay-stillman**
Updated bugFix due to changes in user editor config - setting default width no longer enables full width publihsing.

### CODE REVIEW

**Comment by jay-stillman** [comment]
fixes #173

**Comment by mrueg** [comment]
Is this change backwards compatible to older versions of confluence?

**Comment by jay-stillman** [comment]
@mrueg full-width is the original and how confluence was prior to the new editor. The "default" mode in latest is based on the new editor fixed-width which is only circa 80% wide. The full-width value is backwards compatible  as far as I have seen, do you have an issue running this? In addition to this have left out content-appearance-draft as that is user preference and configured as a profile setting

**Comment by jay-stillman** [comment]
@mrueg also for clarity in May 22 Atlassian fixed the api for fixed-width, however another bug was introduced. A fix was applied in Dec 22 which resulted in allowing either value to the API. The default is "fixed-width" hence causing the issue with full-width in mark when passing "Layout: plain"

**Comment by mrueg** [comment]
Thanks a lot for the clarification @jay-stillman! I haven't seen any issues here, wanted to make sure that it doesn't break things for other users.

**Pull request merged**
