### PR TITLE
allow change of delimiters

### PR DESCRIPTION
**Pull request by Skeeve**
This PR will allow you to change the template delimiters as well as switching off delimiters at all, resulting in an "unparsed" template. See README.md for details.

This also includes PR #191

### CODE REVIEW

**Comment by kovetskiy** [comment]
Could you rebase it?

**Comment by Skeeve** [comment]
Will try.

**Comment by Skeeve** [comment]
> Could you rebase it?

Done

**Comment by Skeeve** [comment]
As rebasing failed three times, I'm closing this. There will be a new PR.

**Pull request closed without merging**
